services:
  dns-checker:
    build: .
    container_name: dns-checker
    ports:
      - "800:80"
    volumes:
      - ./data:/var/www/html/data
      - ./config.php:/var/www/html/config.php
      - ./config-editor.php:/var/www/html/config-editor.php
    restart: unless-stopped
